#!/usr/bin/env bash
#check file exists and check if empty.

if [ -f "school" ]; then
    echo "school file exist";
    if [ -s "school" ]; then
	echo "school file is not empty";
    else
	echo "school file is empty";
    fi
    if [ -r "school" ]; then
	echo "school is a regular file";
    fi
else
    echo "school file does not exist";
fi
